# Site settings
title: Aton's Profile
email: we.grow@mashamba.co
description: > # this means to ignore newlines until "baseurl:"
  Creating a GitHub page profile!
baseurl: "/project-gh-pages"
url: "http://atonb117.github.io"
twitter_username: atonb117
github_username:  atonb117
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
